### ISSUE TITLE
Enchanted books not generating properly in abandoned_mineshaft

### ISSUE THREAD

**Issue by kasekun** [GabrielDja/GD-BetterLoot#1]
Chests are generating with an item called "enchanted-book" rather than with a book that is enchanted

Need to change

`          "name": "minecraft:enchanted_book",`
to
`          "name": "minecraft:book",`

in `abandoned_mineshaft.json` https://github.com/GabrielDja/GD-BetterLoot/blob/301b1421287b2a6c34e0a1218d34c3cda2cb553f/data/minecraft/loot_table/chests/abandoned_mineshaft.json#L102

**Comment by GabrielDja** [comment]
Thank you kasekun, for reporting this problem.
I'll fix it for the next version :D

**Comment by GabrielDja** [comment]
Fixed in v1.0b5: 71cb0080009cfd989b03929628456ba704553e9a
